sudo: required
services:
  - docker

before_install:
  - docker build -t zman13/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true zman13/react-test npm test

after_success:
  - docker build -t zman13/multi-client ./client
  - docker build -t zman13/multi-nginx ./nginx
  - docker build -t zman13/multi-server ./server
  - docker build -t zman13/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push zman13/multi-client 
  - docker push zman13/multi-nginx 
  - docker push zman13/multi-server 
  - docker push zman13/multi-worker

deploy:
  provider: elasticbeanstalk
  region:  us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-938003218147
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY