sudo: required
services:
  - docker

before_install:
  - docker build -t marcziss1/react-test -f ./client/Dockerfile.dev
  
script:
  - docker run -e CI=true marcziss1/react-test npm test

after_install:
  - docker build -t marcziss1/multi-client ./client
  - docker build -t marcziss1/multi-nginx ./nginx
  - docker build -t marcziss1/multi-server ./server
  - docker build -t marcziss1/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push marcziss1/multi-client 
  - docker push marcziss1/multi-nginx 
  - docker push marcziss1/multi-server 
  - docker push marcziss1/multi-worker 